### ISSUE TITLE
Question bar items appear during the drag-n-drop to the Panel

### ISSUE THREAD

**Issue by OlgaLarina** [surveyjs/survey-creator#1371]
![LBwbVrJYRx](https://user-images.githubusercontent.com/14936841/122553780-cc5c0880-d040-11eb-9c1a-2a62daecc823.gif)

**Comment by tsv2013** [comment]
Fixed via the https://github.com/surveyjs/survey-creator/commit/370097e42049f36bec9039d18dca1a674ad9db7f commit - question.scss file:

```CSS
.svc-question__content--selected,
.svc-hovered > .svc-question__content--selected {
  border: 2px solid $secondary;
  & > .svc-question__content-actions {
    display: block;
  }
}
```
