### ISSUE TITLE
DnD: Choices: styles bug

### ISSUE THREAD

**Issue by dmitrykurmanov** [surveyjs/survey-creator#2232]
![image](https://user-images.githubusercontent.com/22315929/142869484-cbae2eda-7121-48f0-bbc8-7046ddd90d1c.png)

**Comment by dmitrykurmanov** [comment]
the css:

```css
.svc-question__content--selected .svc-item-value-wrapper {
  margin-left: calcSize(-5);
}
```
