### ISSUE TITLE
Implement Scrollbar CSS

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#2292]
Scrollbar background should be the same as control background

```css
::-webkit-scrollbar {
  width: 12px;
}

::-webkit-scrollbar-track {
  background: transparent; 
}

::-webkit-scrollbar-thumb {
  border: 4px solid rgba(0, 0, 0, 0);
  background-clip: padding-box;
  border-radius: 32px;
  background-color: #d6d6d6;
}

::-webkit-scrollbar-thumb:hover {
  border: 2px solid rgba(0, 0, 0, 0);
  background-color: #909090;
}
```

![Scrollbar-01](https://user-images.githubusercontent.com/29385489/144252604-03722712-9215-426a-b574-8b83f60e9ec6.png)
![Scrollbar-02](https://user-images.githubusercontent.com/29385489/144252607-35ae698e-bf61-4b6a-bc63-508de26cda92.png)
