### ISSUE TITLE
Input type color bad CSS

### ISSUE THREAD

**Issue by SamMousa** [surveyjs/survey-creator#2545]
### Are you requesting a feature, reporting a bug or ask a question?
Bug

### What is the current behavior?
When adding a custom property of type color to the creator it doesn't render well due to large borders but no intrinsic size.

### What is the expected behavior?
It's a supported type so it should render properly.

### How would you reproduce the current behavior (if this is a bug)?
Add a custom property of type color to an itemvalue type.

#### Provide the test code and the tested page URL (if applicable)
Sample code is in #2500 

![output](https://user-images.githubusercontent.com/547021/149936306-a4924db5-9528-4b66-ab2d-b4133a97a92e.gif)

### Solution
I think a simple solution would be to add some css like:

```css
input[type=color] {
    width: 50px; /** any fixed width should be fine */
    border: none; /* a border makes the color less visible when the element is small */
}
```
