### ISSUE TITLE
Fix string editor issue in Safari

### ISSUE THREAD

**Issue by novikov82** [surveyjs/survey-creator#3017]
In-line editing of (for instance) question titles or choices does not work in Safari (running safari version 14.1.1).

**Comment by novikov82** [comment]
we need to add 
```css
[contenteditable] {
    -webkit-user-select: text;
    user-select: text;
}
```
