### ISSUE TITLE
Adding/Removing items scrolls the creator and hides the header

### ISSUE THREAD

**Issue by JaneGaid** [surveyjs/survey-creator#3419]
From [T10584 - Prevent Scrolling when add or remove element](https://surveyjs.answerdesk.io/internal/ticket/details/T10584)
> when you add a field than he header gets hide because of overflow in the body. This happens due to the scrolling in body. and I want to prevent this body scrolling.

[Example](https://codesandbox.io/s/objective-meadow-100y7t?file=/src/index.js).

**Comment by tsv2013** [comment]
I've checked your plunker.
You set the header size to 180px:
```CSS
.myHeader {
  text-align: center;
  padding: 26px;
  font-size: 30px;
  background: #909090;
  color: #fff;
  height: 180px;
  box-sizing: border-box;
}
```
At the same time you set the root div height to the 100vh and creator height to
```HTML
<div style={{ height: "calc(100vh - 90px)" }}>
```
Thus survey height + header height will be more than screen size.
When one adds or removes question survey creator scrolls to it. Scrolling an element to viewport is performed by a web browser. And if screen content is greater than viewport, it scrolls it is it possible. This why you get header scrolled.

If you change creator height to fit screen size, the issue seems to be fixed:
```HTML
<div style={{ height: "calc(100vh - 100px)" }}>
```

Here is the updated CodeSanbox - https://codesandbox.io/s/youthful-chandrasekhar-37og1b?file=/src/SurveyCreatorComponent.jsx:3001-3048
