### ISSUE TITLE
Survey creator support for global box-sizing border-box css

### ISSUE THREAD

**Issue by hekin1** [surveyjs/survey-creator#3562]
### Are you requesting a feature, reporting a bug or ask a question?
reporting a bug

### What is the current behavior?
The current css for the logic tab, calculating the height of buttons, breaks when page uses `box-sizing: border-box`

More specific this css-rule:

```css
.svc-logic-paneldynamic div.svc-logic-operator {
  height: calc(3 * var(--base-unit, 8px));
}
```

in combination with this global rule:

```css
*, ::after, ::before {
  box-sizing: border-box;
}
```

produces this result:
![bild](https://user-images.githubusercontent.com/14329635/195817516-ac237109-9823-4b5c-9efd-9efa77865d41.png)

### What is the expected behavior?
Removing this rule:

```css
.svc-logic-paneldynamic div.svc-logic-operator {
  height: calc(3 * var(--base-unit, 8px));
}
```

will make the layout OK again for pages that use box-sizing border box globally (Which most pages does).
![bild](https://user-images.githubusercontent.com/14329635/195817993-ad60b997-87bf-47d1-b3a7-67af132416e5.png)

### How would you reproduce the current behavior (if this is a bug)?
Add global page rule:

```css
*, ::after, ::before {
  box-sizing: border-box;
}
```

Then visit the logic tab in survey creator, and press New rule to see the layout error.

Plunkr: https://plnkr.co/edit/5lVOk40xy0MHd7o1

### Specify your

* browser: firefox and chrome
* editor version: latest
