### ISSUE TITLE
Impossible to change the color of a drop-down chevron icon on a design surface

### ISSUE THREAD

**Issue by JaneSjs** [surveyjs/survey-creator#5725]
T19113 - Change icon color 
https://surveyjs.answerdesk.io/internal/ticket/details/T19113
***
It is impossible to change the color of the following icon because the SVG image is applied via a `background-image` attribute.
[View Demo](https://surveyjs.io/survey-creator/examples/edit-user-interface-theme-with-custom-css/)
![image](https://github.com/user-attachments/assets/0a3b9a49-16f5-4247-bab3-89b27c991195)

**Comment by dmitry-kurmanov** [comment]
In `v1.11.10` it is possible by regular CSS since we changed the URL approach to `svg node` and implemented css theme variables. So it will work:

```css
:root {
      --ctr-survey-question-panel-toolbar-item-icon-color: tomato;
    }
```
