### ISSUE TITLE
Custom question adorner action doesn't apply new css on changes

### ISSUE THREAD

**Issue by tsv2013** [surveyjs/survey-creator#6132]
T20859 - Boolean question property doesn't show clear on/off switch
https://surveyjs.answerdesk.io/internal/ticket/details/T20859
***
![Image](https://github.com/user-attachments/assets/f41c05ed-1b6a-4ccf-b49c-b09969c95b9f)

However, with the latest version, the property shows as:
![Image](https://github.com/user-attachments/assets/4ddc805a-ed5d-427d-bfb5-9042644b59eb)

**Comment by JaneSjs** [comment]
We developers researched this issue. It appears that demo uses CSS classes which are no longer available. To change the color of a custom adorner action, add the following CSS class to your application and modify the action's `css` attribute as follows:
```css
.icon-switch-inactive .svc-survey-element-toolbar-item__icon use {
  fill: var(--sjs-general-forecolor-light, var(--foreground-light, #909090));
}
```
```js
css: new SurveyCore.ComputedUpdater(() => question.onOffSwitch ? "icon-switch-inactive" : ""),
```
