### ISSUE TITLE
Width of dropdowns in logic (regression in v1.1.24)

### ISSUE THREAD

**Issue by mkopinsky** [surveyjs/survey-creator#647]
### Are you requesting a feature, reporting a bug or ask a question?

Bug

### What is the current behavior?

In visibleIf (and other logic), the custom_select container is full-width, even though the select itself only occupies part of the width. Aside from looking less good with the other fields on subsequent lines, the caret on the far right to open the select does not work.

![image](https://user-images.githubusercontent.com/591435/72275460-f7485e80-35fb-11ea-9578-6bef2f2c2d16.png)

This was introduced in https://github.com/surveyjs/survey-creator/commit/246af3a7282f919acf46f915ec98b41d66932f8f 

Prior to that, the width of the element was determined by bootstrap's
```css
@media (min-width: 768px)
.form-inline .form-control {
    display: inline-block;
    width: auto;
    vertical-align: middle;
}
```
rule, but now that the svd_custom_select selector is more specific, it's winning out over that bootstrap rule
