### ISSUE TITLE
Cannot make survey-creator display in full height (always has 480px)

### ISSUE THREAD

**Issue by vitexikora** [surveyjs/survey-creator#6696]
**Describe the bug**
New version of survey-creator (react; 1.12.26) is displayed with height of 480px.

Previously (e.g. in 1.12.6) I have used this CSS style:

```css
// full height with no inner scroll
body .svc-flex-row.svc-full-container {
  height: inherit;
}
body .svc-creator__content-wrapper {
  height: inherit;
}
```

To let the creator display in full height.

This is not working now and the CSS currently only breaks the sidebar.

**Steps to reproduce**

1. Go to https://surveyjs.io/create-free-survey
2. In DOM Inspector, remove the calculated height from `#creator` (imagine you dont want it fullscreen, but in real full height, along with other form options)
3. See that the editor now has height of 480px

**Expected behavior**
The editor should grow to real height based on size of the form. Or at least there should be a configuration option to turn this behavior on.

**Please complete the following information:**
- Browser: firefox
- Browser version: 136
- JS framework/library: React
- SurveyJS version: 1.12.26
- Device: PC
